<?xml version="1.0" encoding="utf-8" standalone="yes" ?>

<!DOCTYPE Allpersons [

<!ELEMENT Allpersons (person*)>
<!ELEMENT person (name,email,phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

]>

<Allpersons>
    <person>
        <name>Yahya</name>
        <email>contact@yahya.com</email>
        <phone>15001458</phone>
    </person>
</Allpersons>